ChannelID = "C:\\untitled\WorkBotToGit\Slack\JsonFiles\ChannelID.txt"
Echat= "C:\\untitled\WorkBotToGit\Slack\JsonFiles\Echat.json"
Ecoding ="C:\\untitled\WorkBotToGit\Slack\JsonFiles\Ecoding.json"
Locations = "C:\\untitled\WorkBotToGit\Slack\JsonFiles\Locations.json"
TelegMessage = "C:\\untitled\WorkBotToGit\Slack\JsonFiles\TelegMessage.json"
test = "C:\\untitled\WorkBotToGit\Slack\JsonFiles\\test.txt"
