ChanneliD = "E:\\untitled\WorkBotToGit\Slack\JsonFiles\ChannelID.txt"
Echat= "E:\\untitled\WorkBotToGit\Slack\JsonFiles\Echat.json"
Ecoding ="E:\\untitled\WorkBotToGit\Slack\JsonFiles\Ecoding.json"
Locations = "E:\\untitled\WorkBotToGit\Slack\JsonFiles\Locations.json"
TelegMessage = "E:\\untitled\WorkBotToGit\Slack\JsonFiles\TelegMessage.json"
test = "E:\\untitled\WorkBotToGit\Slack\JsonFiles\\test.txt"
Errors = "E:\\untitled\WorkBotToGit\Slack\JsonFiles\\errors.json"
